site_name: DuBlast
site_url: http://dublast.rxlab.guide
repo_url: https://github.com/RxLaboratory/DuBLF_DuBlast/
edit_uri: edit/master/src-docs/docs/
site_description: The DuBlast comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2022 <a href="https://rxlaboratory.org">Rainbox Laboratory</a> and <a href="https://duduf.com">Nicolas Dufresne</a>'
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - toc
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - v2.1.1: index.md
    - Settings: settings.md
    - ...:
        - Changelog: changelog.md
        - License:
            - GNU GPLv3: gnu-gpl.md
            - Documentation license: doc-license.md
        - Contact: http://contact.rxlab.info
        - Donate: http://donate.rxlab.info
